### PR TITLE
Ported to Plasma 6

### PR DESCRIPTION
**Pull request by dhruv8sh**
Bhai banata h kuch to paanch minute to de diya kr kisi kaam ko.

### CODE REVIEW

**Comment by Prayag2** [comment]
Thanks for the contribution but you could have avoided being rude :)
The reason I haven't updated any of my Plasma widgets is because I don't use Plasma anymore. Contributions are still welcome though!

**Comment by dhruv8sh** [comment]
It wasn't meant to rude, rather playful.
You can mention that you won't be updating the applets on the README though.
Also, I will add this release to the KDE Store for now.

**Comment by Prayag2** [comment]
No need to upload it to the KDE Store as that will cause duplicate
listings. I'll update the version there.

**Comment by dhruv8sh** [comment]
The listing for Plasma 5 and Plasma 6 applets are in different sections. Applets for Plasma 5 will not show up in Plasma 6 "Add Widgets" popup.

Also, if you edit and update the previous listing it might break the applet for people who are still using Plasma 5.

**Comment by Prayag2** [comment]
Oh. Don't worry I'll update all of them and upload updated versions today
itself :)

**Comment by dhruv8sh** [comment]
Ok, I'll take off the listing I made.

**Comment by Prayag2** [comment]
Thanks again, for the contribution (and giving me the motivation to update other plasmoids)!!
I have created new listings for two of my plasmoids (Minimalist Clock and Modern Clock). I'll update the other plasmoids soon (they need several bug fixes)!

**Comment by dhruv8sh** [comment]
Ask me for help if you need it.
I would be really interested in porting the Control Center.

**Pull request merged**
